id: P001756
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21873
  title: བོད་ཀྱི་ཤེར་རྟོགས་རིག་པའི་རིགས་ཤེས།
  author: ''
  volumes:
    14014fb1cfdb4d398c7b4844546057fd:
      image_group_id: I1KG23233
      title: ''
      volume_number: 1
      total_pages: 268
      base_file: v001.txt
